spring.application.name=todo-springboot
#
# database config
#
spring.datasource.url=jdbc:postgresql://localhost:5432/todo?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=rKEq9Pa4b3uOZ7WRS375
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

spring.mvc.servlet.path=/api

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/todo
logging.level.org.springframework.security=TRACE

# path to store the log
logging.file.name=logs/error.log
logging.level.root=ERROR

server.port=8081
